apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: bohemian-cms-dev
  namespace: {{ .Values.application.namespace}}
  labels:
    app: bohemian-cms-dev
   
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: bohemian-cms-dev
      release: bohemian-cms-dev
  template:
    metadata:
      labels:
        app: bohemian-cms-dev
        release: bohemian-cms-dev
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}     
          ports:
            - nodePort: 5844
              containerPort: 1985
              targetPort: 80
              protocol: TCP
              name: http
          livenessProbe:
            httpGet:
              path: {{ .Values.deployment.path | quote}}
              port: http
              initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: {{ .Values.deployment.path | quote}}
              port: http
              initialDelaySeconds: 30


