# {{- if .Values.ingress.enabled -}}
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: dev-boh-ingress-1
#   namespace: {{ .Values.application.namespace}}
# spec:
#   tls:
#   - secretName: boh-dev-tls-secret
#   rules:
#   - host: dev.bohemian-cms.com
#     http:
#       paths:
#       - path: 
#         backend:
#           serviceName: dev-boh-cms-service-1
#           servicePort: 1985

# {{- end }}

