apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: tls-secret
spec:
  secretName: tls-secret
  dnsNames:
  - dev.bohemian-cms.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - dev.bohemian-cms.com
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer