apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: antgio-staging
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ant@onedigitalvision.com

    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging

    # ACME DNS-01 provider configurations
    dns01:
      providers:
        - name: clouddns
          clouddns:
            serviceAccountSecretRef:
              name: clouddns
              key: clouddns.key.json
            # The project in which to update the DNS zone
            project: onedigitalvision