apiVersion: v1
kind: Service
metadata:
  name: Bohemian-cms-dev
  namespace: {{ .Values.application.namespace}}
  labels:
    app: Bohemian-cms-dev
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: Bohemian-cms-dev
    release: Bohemian-cms-dev
